version: "3.7"
services:
  app:
    build: 
      args: 
        user: dean
        uid: 1001
      context: ./.docker
      dockerfile: Dockerfile
    image: laravelapp
    container_name: laravelapp-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      REDIS_HOST: redis   # Set the Redis host
    networks:
      - laravelapp

  db:
    image: mysql:5.7
    container_name: laravelapp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'lara_db'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'lara_password'
      MYSQL_USER: 'lara_user'
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravelapp

  nginx:
    image: nginx:1.17-alpine
    container_name: laravelapp-nginx
    restart: unless-stopped
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - laravelapp
  redis:
    image: redis:latest
    container_name: laravelapp-redis
    restart: unless-stopped
    networks:
      - laravelapp

  minio:
    image: bitnami/minio:latest
    container_name: laravelapp-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - laravelapp
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravelapp-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"  # Cổng truy cập
    environment:

      PMA_HOST: db  # Tên của dịch vụ MySQL trong Docker Compose
    networks:
      - laravelapp

networks: 
  laravelapp:
    driver: bridge

volumes:
  minio_data:
